#pragma once

#define MILKDAWP_VERSION_MAJOR 0
#define MILKDAWP_VERSION_MINOR 0
#define MILKDAWP_VERSION_PATCH 1

#define STRINGIFY_HELPER(x) #x
#define STRINGIFY(x) STRINGIFY_HELPER(x)
#define MILKDAWP_VERSION_STRING STRINGIFY(MILKDAWP_VERSION_MAJOR) "." STRINGIFY(MILKDAWP_VERSION_MINOR) "." STRINGIFY(MILKDAWP_VERSION_PATCH)
